baseURL = 'https://example.org/'
languageCode = 'en-gb'
title = 'United Kingdom Special Forces'
theme = 'uksf-mod-theme'
publishDir = 'docs'
canonifyurls = true

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[params]
  govuk = true
  industrial_gothic_enabled = true
  unit_theme = 'SAS' # Default: SAS. Options: SAS, SBS, SRR, SFSG, JSFAW
  phase = 'alpha'
  feedbackurl = 'https://recruitment.mod.gov.uk/feedback'
  builtby = 'Directorate of Special Forces'
  builtbyurl = 'https://www.gov.uk/government/groups/directorate-of-special-forces'

[module]
  [module.hugoVersion]
    extended = true
    min = '0.154.0'