baseURL = 'https://example.org/'
languageCode = 'en-gb'
title = 'UKSF Taskforce Alpha'
theme = 'uksf-mod-theme'
publishDir = 'docs'
canonifyurls = true

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[params]
  govuk = false
  industrial_gothic_enabled = true
  unit_theme = 'SAS' # Default: SAS. Options: SAS, SBS, SRR, SFSG, JSFAW
  phase = 'operational'
  feedbackurl = '#'
  builtby = 'UKSF Taskforce Alpha'
  builtbyurl = 'https://discord.gg/2jNqa3zPRH'

[params.unitcommander]
  enabled = true
  community_id = "" # Paste your Community ID here
  bot_token = ""    # Paste your Bot Token here (Format: "Bot YOUR_TOKEN")

[module]
  [module.hugoVersion]
    extended = true
    min = '0.154.0'