baseURL = 'https://example.org/'
languageCode = 'en-gb'
title = 'UKSF Taskforce Alpha'
theme = 'uksf-mod-theme'
publishDir = 'docs'
canonifyurls = true

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[params]
  govuk = false
  industrial_gothic_enabled = true
  unit_theme = 'SAS' # Default: SAS. Options: SAS, SBS, SRR, SFSG, JSFAW
  phase = 'operational'
  feedbackurl = '#'
  builtby = 'UKSF Taskforce Alpha'
  builtbyurl = 'https://discord.gg/2jNqa3zPRH'

[params.unitcommander]
  enabled = true
  community_id = "722" # Paste your Community ID here
  bot_token = "eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJVbml0IENvbW1hbmRlciIsImlhdCI6MTc2OTcxNjY3MX0.F51U2FxtFVB2blAeHvq3KKBs0GC-u0R16V5hZBIlX9Q"    # Paste your Bot Token here

[params.intelligence]
  map_path = "icons/UKSF-MAP.png"
  intel_map_path = "icons/intelligence-map.png"
  registry_node = "UK JSFC 01"
  intel_node = "PRIMARY_ALPHA"
  network = "RSIS_GLOBAL"
  sys_status = "STABLE"
  node_id = "JSFC-01"
  classification = "OFFICIAL_SENSITIVE"

[params.discord]
  enabled = true
  server_id = "1321236261553573928"

[module]
  [module.hugoVersion]
    extended = true
    min = '0.154.0'