baseURL = 'https://example.org/'
languageCode = 'en-gb'
title = 'UKSF Example Site'
theme = 'uksf-mod-theme'

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[params]
  unit_theme = 'global'
  builtby = 'Directorate of Special Forces'

[[menus.main]]
  name = "SAS"
  url = "/sas/"
  weight = 10

[[menus.main]]
  name = "SBS"
  url = "/sbs/"
  weight = 20

[[menus.main]]
  name = "Rangers"
  url = "/rangers/"
  weight = 25

[[menus.main]]
  name = "SFSG"
  url = "/sfsg/"
  weight = 40

[[menus.main]]
  name = "JSFAW"
  url = "/jsfaw/"
  weight = 50

[[menus.main]]
  name = "Recruitment"
  url = "/recruitment/"
  weight = 60
