baseURL = 'https://example.org/'
languageCode = 'en-gb'
title = 'Taskforce Alpha // UKSF Milsim'
theme = 'uksf-mod-theme'

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[params]
  unit_theme = 'global'
  builtby = 'Taskforce Alpha // Milsim Community'

[[menus.main]]
  name = "SAS"
  url = "/sas/"
  weight = 10

[[menus.main]]
  name = "SBS"
  url = "/sbs/"
  weight = 20

[[menus.main]]
  name = "SRR"
  url = "/srr/"
  weight = 30

[[menus.main]]
  name = "SFSG"
  url = "/sfsg/"
  weight = 40

[[menus.main]]
  name = "JSFAW"
  url = "/jsfaw/"
  weight = 50

[[menus.main]]
  name = "Med Det"
  url = "/med-det/"
  weight = 55

[[menus.main]]
  name = "HQ"
  url = "/tfhq/"
  weight = 58

[[menus.main]]
  name = "Join"
  url = "/recruitment/"
  weight = 60
