baseURL = '/'
languageCode = 'en-gb'
title = 'UKSF Taskforce Alpha | Joint Force Command'
publishDir = 'public'
canonifyurls = true
buildFuture = true

[module]
  [module.hugoVersion]
    extended = true
    min = '0.154.0'
  [[module.mounts]]
    source = 'assets'
    target = 'assets'
  [[module.mounts]]
    source = 'node_modules'
    target = 'assets/node_modules'
  [[module.mounts]]
    source = 'node_modules/@defencedigital/css-framework'
    target = 'assets/node_modules/@defencedigital/css-framework'

# ==========================================
# MARKUP PROTOCOLS (G6 COMMUNICATIONS)
# ==========================================
[markup]
  [markup.goldmark]
    [markup.goldmark.extensions]
      definitionList = true
      footnote = true
      linkify = true
      strikethrough = true
      table = true
      taskList = true
      typographer = true # Enhanced British punctuation
    [markup.goldmark.parser]
      attribute = true # Allows {.class} in markdown
      autoHeadingIDType = 'github'
    [markup.goldmark.renderer]
      hardWraps = false
      unsafe = true # Required for tactical components and embedded HTML
      xhtml = false

  [markup.tableOfContents]
    endLevel = 3
    ordered = false
    startLevel = 2

# ==========================================
# GLOBAL TACTICAL PARAMETERS
# ==========================================
[params]
  # G1 - PERSONNEL & ADMINISTRATION
  builtby = 'Taskforce Command'
  builtbyurl = 'https://discord.gg/2jNqa3zPRH'
  recruitment_status = 'OPEN_SELECTION'
  govuk = true # Activates official font behaviors and the HMG "Superior Rule"
  phase = 'alpha' # Displays the mandatory GDS phase banner for new services
  
  # G2 - INTELLIGENCE & SECURITY
  classification = 'OFFICIAL_SENSITIVE'
  security_clearance = 'STRATEGIC_LEVEL_ALPHA'
  
  # G3 - OPERATIONS & READINESS
  op_readiness = 'OP_READY'
  
  # TECHNICAL INTERFACE SETTINGS
  industrial_gothic_enabled = true
  feedbackurl = '#'

[params.unitcommander]
  enabled = true
  community_ref = "722"
  # G6 SIGNAL TOKEN - DO NOT COMMIT SECRETS
  signal_token = "REPLACE_WITH_ACTUAL_TOKEN"

[params.intelligence]
  # G2 ASSET MAPPING
  map_path = "icons/UKSF-MAP.png"
  intel_map_path = "icons/intelligence-map.png"
  registry_node = "UK JSFC 01"
  g2_uplink_node = "PRIMARY_ALPHA"
  signal_net = "RSIS_GLOBAL"
  sys_status = "STABLE"
  node_ref = "JSFC-01"

[params.discord]
  enabled = true
  server_id = "1321236261553573928"

# ==========================================
# MENUS
# ==========================================
[[menus.main]]
  name = "SAS"
  url = "/sas/"
  weight = 10

[[menus.main]]
  name = "SBS"
  url = "/sbs/"
  weight = 20

[[menus.main]]
  name = "ASOB"
  url = "/asob/"
  weight = 25

[[menus.main]]
  name = "SFSG"
  url = "/sfsg/"
  weight = 40

[[menus.main]]
  name = "JSFAW"
  url = "/jsfaw/"
  weight = 50

[[menus.main]]
  name = "RAMC"
  url = "/med-det/"
  weight = 55

[[menus.main]]
  name = "Recruitment"
  url = "/recruitment/"
  weight = 60
